#ifndef _RTW88_FW_BLOBS_H
#define _RTW88_FW_BLOBS_H

#include <stdint.h>
#include <stddef.h>

struct rtw88_fw_blob {
    const char    *name;
    const uint8_t *data;           /* zlib-compressed */
    size_t         compressed_size;
    size_t         original_size;
};

/* Null-terminated table generated by gen_fw_blobs.py */
extern const struct rtw88_fw_blob rtw88_fw_blobs[];

#endif /* _RTW88_FW_BLOBS_H */
