#!/usr/bin/env python3
# gen_fw_blobs.py — generate fw_blobs.c from firmware/*.bin
# Usage: python3 gen_fw_blobs.py <fw_dir> <output.c>

import sys, os, zlib

fw_dir  = sys.argv[1]
out_c   = sys.argv[2]

bins = sorted(f for f in os.listdir(fw_dir) if f.endswith('.bin'))
if not bins:
    # No firmware — emit an empty table so the build still works
    with open(out_c, 'w') as f:
        f.write('/* No firmware blobs — add *.bin to firmware/ and rebuild */\n')
        f.write('#include "fw_blobs.h"\n')
        f.write('const struct rtw88_fw_blob rtw88_fw_blobs[] = { { 0, 0, 0, 0 } };\n')
    sys.exit(0)

lines = []
lines.append('/* Auto-generated by gen_fw_blobs.py — do not edit */')
lines.append('#include <stdint.h>')
lines.append('#include <stddef.h>')
lines.append('#include "fw_blobs.h"')
lines.append('')

entries = []
for name in bins:
    path = os.path.join(fw_dir, name)
    raw  = open(path, 'rb').read()
    comp = zlib.compress(raw, 9)

    sym = 'fw_' + name.replace('.', '_').replace('-', '_')
    entries.append((name, sym, len(comp), len(raw)))

    # emit as C array, 16 bytes per line
    lines.append(f'static const uint8_t {sym}[] = {{')
    for i in range(0, len(comp), 16):
        chunk = comp[i:i+16]
        hex_str = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f'    {hex_str},')
    lines.append('};')
    lines.append('')

lines.append('const struct rtw88_fw_blob rtw88_fw_blobs[] = {')
for name, sym, csz, osz in entries:
    lines.append(f'    {{ "{name}", {sym}, {csz}, {osz} }},')
lines.append('    { 0, 0, 0, 0 }')
lines.append('};')
lines.append('')

with open(out_c, 'w') as f:
    f.write('\n'.join(lines) + '\n')

total_orig = sum(e[3] for e in entries)
total_comp = sum(e[2] for e in entries)
print(f'  GEN  {out_c}: {len(bins)} blobs, '
      f'{total_orig//1024}KB → {total_comp//1024}KB compressed')
